;;; ar-bracketlist-atpt-tests.el --- ar-bracketlist-atpt-tests -*- lexical-binding: t; -*-

;; Copyright (C) 2015-2025  Andreas Röhler
;; Author: Andreas Roehler <andreas.roehler@online.de>
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from python-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(ert-deftest ar-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (length (ar-list-atpt))))))

(ert-deftest ar-bracketlist-bounds-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (and (eq 2 (car (ar-bounds-of-list-atpt)))(eq 8 (cdr (ar-bounds-of-list-atpt)))))))

(ert-deftest ar-bracketlist-beginning-position-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 2 (ar-list-beginning-position-atpt)))))

(ert-deftest ar-bracketlist-end-position-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 8 (ar-list-end-position-atpt)))))

(ert-deftest ar-bracketlist-beginning-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-beginning-of-list-atpt)
    (should (eq 2 (point)))))

(ert-deftest ar-bracketlist-end-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    ;; (skip-syntax-forward "^(")
    (ar-end-of-list-atpt)
    (should (eq (char-after) ?\]))))

(ert-deftest ar-in-bracketlist-p-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (ar-in-list-p-atpt))))

(ert-deftest ar-bracketlength-of-list-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (ar-length-of-list-atpt)))
    (goto-char 1)
    (should (eq 8 (ar-length-of-list-atpt)))))

(ert-deftest ar-bracketlist-copy-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (length (ar-copy-list-atpt))))))

(ert-deftest ar-delete-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-delete-list-atpt)
    (should (eq 2 (ar-length-of-list-atpt)))))

(ert-deftest ar-doublequote-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doublequote-list-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-slash-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (length (ar-list-atpt))))))

(ert-deftest ar-doublebackslash-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doublebackslash-list-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-doubleslash-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doubleslash-list-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-doublebackslashparen-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doublebackslashparen-list-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-slashparen-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-slashparen-list-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-dollar-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-dollar-list-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-equalize-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-equalize-list-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-greaterangle-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-greaterangle-list-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-lesserangle-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-lesserangle-list-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-backslash-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-backslash-list-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-backtick-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-backtick-list-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-brace-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-brace-list-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-bracket-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-bracket-list-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-hyphen-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-hyphen-list-atpt)
    (should (eq (char-before) ?\-))))

(ert-deftest ar-mark-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-mark-list-atpt)
    (should (eq 2 (region-beginning)))
    (should (eq 8 (region-end)))))

(ert-deftest ar-kill-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-kill-list-atpt)
    (should (eq 2 (ar-length-of-list-atpt)))))

(ert-deftest ar-parentize-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-parentize-list-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-separate-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 2)
    ;; (skip-syntax-forward "^(")
    (ar-separate-list-atpt)
    (end-of-line)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-singlequote-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-singlequote-list-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-triplequotesq-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-triplequotesq-list-atpt)
    (should (looking-back "'''"))))

(ert-deftest ar-triplequotedq-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-triplequotedq-list-atpt)
    (should (looking-back "\"\"\""))))

(ert-deftest ar-trim-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-trim-list-atpt)
    (should (eq (char-after) ?1))))

(ert-deftest ar-left-trim-bracketlist-atpt-test ()
  (py-test-with-temp-buffer-point-min
      "[[1, 2]]\n"
    (goto-char (point-min))
    (forward-char 1)
    (ar-left-trim-list-atpt)
    (should (eq (char-after) ?1))))

(ert-deftest ar-double-bracketlist-atpt-test-2kUrYf ()
  (ar-test-with-temp-buffer
      "[[http://www.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html]] and"
      (search-backward "B" nil t 1)
    (should (eq 2 (car (ar-bounds-of-bracketed-atpt))))))

(ert-deftest ar-double-bracketlist-atpt-test-BLAUkn ()
  (ar-test-with-temp-buffer
      "[[http://www.cs.miami.edu/~tptp/TPTP/SyntaxBNF.html]] and"
      (search-backward "B" nil t 1)
    (should (eq 53 (cdr (ar-bounds-of-bracketed-atpt))))))


      ;; (should (eq 53 (cadr (cadr bounds)))))))

(provide 'ar-bracketlist-atpt-tests)

;;; ar-bracketlist-atpt-tests.el ends here
