;;; ar-delimited2delimited-tests.el --- delimited to delimited tests -*- lexical-binding: t; -*-

;; Copyright (C) 2015-2016 Andreas Röhler

;; Author: Andreas Röhler <andreas.roehler@online.de>
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from python-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(ert-deftest ar-braced2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-braced2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-braced2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-braced2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-braced2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-braced2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-braced2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-braced2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-braced2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-braced2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-braced2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-braced2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-bracketed2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-bracketed2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-bracketed2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-bracketed2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-bracketed2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-bracketed2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-bracketed2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-bracketed2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-bracketed2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-bracketed2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-bracketed2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-bracketed2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-lesser-angled2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-lesser-angled2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-lesser-angled2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-lesser-angled2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-lesser-angled2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-lesser-angled2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-lesser-angled2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-lesser-angled2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-lesser-angled2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-lesser-angled2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-lesser-angled2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-lesser-angled2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-greater-angled2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-greater-angled2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-greater-angled2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-greater-angled2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-greater-angled2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-greater-angled2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-greater-angled2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-greater-angled2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-greater-angled2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-greater-angled2stared-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-greater-angled2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-greater-angled2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-left-right-singlequoted2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-left-right-singlequoted2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-left-right-singlequoted2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-left-right-singlequoted2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-left-right-singlequoted2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-left-right-singlequoted2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-left-right-singlequoted2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-left-right-singlequoted2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-left-right-singlequoted2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-left-right-singlequoted2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-left-right-singlequoted2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-left-right-singlequoted2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-parentized2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-parentized2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-parentized2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-parentized2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-parentized2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-parentized2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-parentized2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-parentized2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-parentized2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-parentized2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-parentized2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-parentized2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-backslashed2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-backslashed2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-backslashed2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-backslashed2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-backslashed2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-backslashed2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-backticked2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-backticked2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-backticked2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-backticked2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-backticked2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-backticked2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-coloned2braced-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-coloned2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-coloned2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-coloned2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-coloned2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-coloned2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-dollared2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-dollared2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-dollared2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-dollared2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-dollared2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-dollared2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-doublequoted2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-doublequoted2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-doublequoted2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-doublequoted2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-doublequoted2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-doublequoted2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-equalized2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-equalized2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-equalized2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-equalized2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-equalized2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-equalized2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-hyphened2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-hyphened2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-hyphened2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-hyphened2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-hyphened2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-hyphened2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-singlequoted2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-singlequoted2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-singlequoted2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-singlequoted2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-singlequoted2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-singlequoted2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-slashed2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-slashed2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-slashed2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-slashed2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-slashed2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-slashed2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-stared2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-stared2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-stared2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-stared2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-stared2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-stared2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-underscored2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-underscored2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-underscored2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-underscored2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-underscored2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-underscored2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-whitespaced2braced-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-whitespaced2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-whitespaced2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-whitespaced2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-whitespaced2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-whitespaced2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-braced2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-braced2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-braced2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-braced2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-braced2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "{asdf}"
    (forward-char -2)
    (ar-braced2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-bracketed2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-bracketed2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-bracketed2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-bracketed2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-bracketed2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "[asdf]"
    (forward-char -2)
    (ar-bracketed2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-lesser-angled2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-lesser-angled2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-lesser-angled2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-lesser-angled2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-lesser-angled2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "<asdf>"
    (forward-char -2)
    (ar-lesser-angled2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-greater-angled2braced-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-greater-angled2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-greater-angled2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-greater-angled2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-greater-angled2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    ">asdf<"
    (forward-char -2)
    (ar-greater-angled2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-left-right-singlequoted2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-left-right-singlequoted2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-left-right-singlequoted2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-left-right-singlequoted2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-left-right-singlequoted2parentized-atpt-test ()
  (ar-test-with-temp-buffer
    "‘asdf’"
    (forward-char -2)
    (ar-left-right-singlequoted2parentized-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-parentized2braced-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2braced-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-parentized2bracketed-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2bracketed-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-parentized2lesser-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2lesser-angled-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-parentized2greater-angled-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2greater-angled-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-parentized2left-right-singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "(asdf)"
    (forward-char -2)
    (ar-parentized2left-right-singlequoted-atpt)
    (should (eq (char-before) ?’))))

(ert-deftest ar-backslashed2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-backslashed2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-backslashed2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-backslashed2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-backslashed2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-backslashed2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-backslashed2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-backslashed2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-backslashed2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-backslashed2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-backslashed2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "\\asdf\\"
    (forward-char -2)
    (ar-backslashed2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-backticked2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-backticked2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-backticked2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-backticked2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-backticked2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-backticked2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-backticked2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-backticked2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-backticked2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-backticked2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-backticked2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "`asdf`"
    (forward-char -2)
    (ar-backticked2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-coloned2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-coloned2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-coloned2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-coloned2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-coloned2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-coloned2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-coloned2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-coloned2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-coloned2stared-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-coloned2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-coloned2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    ":asdf:"
    (forward-char -2)
    (ar-coloned2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-dollared2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-dollared2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-dollared2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-dollared2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-dollared2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-dollared2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-dollared2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-dollared2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-dollared2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-dollared2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-dollared2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "$asdf$"
    (forward-char -2)
    (ar-dollared2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-doublequoted2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-doublequoted2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-doublequoted2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-doublequoted2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-doublequoted2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-doublequoted2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-doublequoted2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-doublequoted2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-doublequoted2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-doublequoted2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-doublequoted2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "\"asdf\""
    (forward-char -2)
    (ar-doublequoted2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-equalized2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-equalized2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-equalized2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-equalized2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-equalized2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-equalized2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-equalized2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-equalized2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-equalized2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-equalized2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-equalized2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "=asdf="
    (forward-char -2)
    (ar-equalized2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-hyphened2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-hyphened2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-hyphened2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-hyphened2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-hyphened2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-hyphened2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-hyphened2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-hyphened2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-hyphened2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-hyphened2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-hyphened2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "-asdf-"
    (forward-char -2)
    (ar-hyphened2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-singlequoted2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-singlequoted2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-singlequoted2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-singlequoted2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-singlequoted2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-singlequoted2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-singlequoted2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-singlequoted2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-singlequoted2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-singlequoted2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-singlequoted2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "'asdf'"
    (forward-char -2)
    (ar-singlequoted2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-slashed2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-slashed2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-slashed2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-slashed2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-slashed2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-slashed2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-slashed2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-slashed2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-slashed2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-slashed2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-slashed2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "/asdf/"
    (forward-char -2)
    (ar-slashed2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-stared2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-stared2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-stared2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-stared2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-stared2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-stared2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-stared2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-stared2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-stared2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-stared2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2underscored-atpt)
    (should (eq (char-before) ?_))))

(ert-deftest ar-stared2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "*asdf*"
    (forward-char -2)
    (ar-stared2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-underscored2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-underscored2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-underscored2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-underscored2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-underscored2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-underscored2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-underscored2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-underscored2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-underscored2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-underscored2stared-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-underscored2whitespaced-atpt-test ()
  (ar-test-with-temp-buffer
    "_asdf_"
    (forward-char -2)
    (ar-underscored2whitespaced-atpt)
    (should (eq (char-before) ? ))))

(ert-deftest ar-whitespaced2backslashed-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2backslashed-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-whitespaced2backticked-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2backticked-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-whitespaced2coloned-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2coloned-atpt)
    (should (eq (char-before) ?:))))

(ert-deftest ar-whitespaced2dollared-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2dollared-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-whitespaced2doublequoted-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2doublequoted-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-whitespaced2equalized-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2equalized-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-whitespaced2hyphened-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2hyphened-atpt)
    (should (eq (char-before) ?-))))

(ert-deftest ar-whitespaced2singlequoted-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2singlequoted-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-whitespaced2slashed-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2slashed-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-whitespaced2stared-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2stared-atpt)
    (should (eq (char-before) ?*))))

(ert-deftest ar-whitespaced2underscored-atpt-test ()
  (ar-test-with-temp-buffer
    " asdf "
    (forward-char -2)
    (ar-whitespaced2underscored-atpt)
    (should (eq (char-before) ?_))))

(provide 'ar-delimited2delimited-tests)
;;; ar-delimited2delimited-tests.el ends here
