;;; ar-list-atpt-bracket-ert-tests.el --- ar-list-atpt-bracket-tests

;; Copyright (C) 2015  Andreas Roehler
;; Author: Andreas Roehler <andreas.roehler@online.de>
;; Keywords: languages, convenience

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; This program is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; Commentary:

;; This file is generated by function from python-mode-utils.el - see in
;; directory devel. Edits here might not be persistent.

;;; Code:

(ert-deftest ar-list-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (length (ar-list-atpt))))))

(ert-deftest ar-list-bounds-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (and (eq 2 (caar (ar-bounds-of-list-atpt)))(eq 8 (cdr (cadr (ar-bounds-of-list-atpt))))))))

(ert-deftest ar-list-beginning-position-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 2 (ar-list-beginning-position-atpt)))))

(ert-deftest ar-list-end-position-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 8 (ar-list-end-position-atpt)))))

(ert-deftest ar-list-beginning-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-list-beginning-atpt)
    (should (eq 2 (point)))))

(ert-deftest ar-list-end-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-list-end-atpt)
    (should (eq 7 (point)))))

(ert-deftest ar-list-in-p-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (ar-list-in-p-atpt))))

(ert-deftest ar-list-length-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (ar-list-length-atpt)))
    (goto-char 1)
    (should (eq 8 (ar-list-length-atpt)))))

(ert-deftest ar-list-copy-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (length (ar-copy-list-atpt))))))

(ert-deftest ar-delete-list-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-delete-list-atpt)
    (should (eq 2 (ar-length-of-list-atpt)))))

(ert-deftest ar-list-doublequote-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doublequote-list-atpt)
    (should (eq (char-before) ?\"))))

(ert-deftest ar-list-slash-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (should (eq 6 (length (ar-list-atpt))))))

(ert-deftest ar-list-doublebackslash-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doublebackslash-list-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-list-doubleslash-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doubleslash-list-atpt)
    (should (eq (char-before) ?/))))

(ert-deftest ar-list-doublebackslashparen-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-doublebackslash-list-paren-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-list-slashparen-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-slashparen-list-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-list-dollar-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-dollar-list-atpt)
    (should (eq (char-before) ?$))))

(ert-deftest ar-list-equalize-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-equalize-list-atpt)
    (should (eq (char-before) ?=))))

(ert-deftest ar-list-greaterangle-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-greaterangle-list-atpt)
    (should (eq (char-before) ?<))))

(ert-deftest ar-list-lesserangle-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-lesserangle-list-atpt)
    (should (eq (char-before) ?>))))

(ert-deftest ar-list-backslash-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-backslash-list-atpt)
    (should (eq (char-before) ?\\))))

(ert-deftest ar-list-backtick-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-backtick-list-atpt)
    (should (eq (char-before) ?`))))

(ert-deftest ar-list-brace-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-brace-list-atpt)
    (should (eq (char-before) ?}))))

(ert-deftest ar-list-bracket-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-bracket-list-atpt)
    (should (eq (char-before) ?\]))))

(ert-deftest ar-list-hyphen-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-hyphen-list-atpt)
    (should (eq (char-before) ?\-))))

(ert-deftest ar-list-mark-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-mark-list-atpt)
    (should (eq 2 (region-beginning)))
    (should (eq 8 (region-end)))))

(ert-deftest ar-list-kill-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-kill-list-atpt)
    (should (eq 2 (ar-length-of-list-atpt)))))

(ert-deftest ar-list-parentize-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-parentize-list-atpt)
    (should (eq (char-before) ?\)))))

(ert-deftest ar-list-separate-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-separate-list-atpt)
    (should (looking-back "^ +"))
    (end-of-line)
    (should (eq (char-after) 10))))

(ert-deftest ar-list-singlequote-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-singlequote-list-atpt)
    (should (eq (char-before) ?'))))

(ert-deftest ar-list-triplequotesq-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-triplequotesq-list-atpt)
    (should (looking-back "'''"))))

(ert-deftest ar-list-triplequotedq-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-triplequotedq-list-atpt)
    (should (looking-back "\"\"\""))))

(ert-deftest ar-list-trim-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-list-trim-atpt)
    (should (eq (char-after) ?1))))

(ert-deftest ar-list-left-trim-atpt-bracket-test ()
  (ar-test-with-python-buffer-point-min
      "[[1, 2]]\n"
    (forward-char 1)
    (skip-syntax-forward "^(")
    (ar-list-left-trim-atpt)
    (should (eq (char-after) ?1))))



(provide 'ar-list-atpt-bracket-ert-tests)
