version: 2.1

aktion:
  echo "Gebe Umgebung aus" 
  ls -lart

jobs:
  thing-at-point-utils:
    docker:
      # - image: ubuntu-2004:202010-01
      - image: silex/emacs:27.2
    working_directory: ~/thing-at-point-utils
    steps:
      - run: apt update && apt install -y git ssh emacs
      - checkout
      - run:
          name: Umgebung
          command:
            echo "Gebe Umgebung aus"; ls -lart

      - run:
          name: ERT tests
          command: |
            emacs -Q --batch \
            --eval "(message (emacs-version))" \
            --eval "(message (getenv \"PWD\"))" \
            --eval "(setq python-indent-offset 4)" \
            --eval "(setq ar-debug-p nil)" \
            --eval "(setq python-indent-guess-indent-offset nil)" \
            --eval "(setq python-indent-guess-indent-offset-verbose nil)" \
            --eval "(load (expand-file-name \"ar-subr.el\"))" \
            --eval "(load (expand-file-name \"ar-beg-end.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-utils-map.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-basic-definitions.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-utils-core.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-utils.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-highlight.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-transform-delimited.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-unpaired-delimited-list-in-rest-list.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-classes-in-rest-list.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-delimited-list-in-counts-list.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-classes-in-delimited-list.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-unpaired-delimited-list-in-delimited-list.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-peel.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-count-ratio.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-transform-generic-delimited.el\"))" \
            --eval "(load (expand-file-name \"ar-translate-paired-delimiters.el\"))" \
            --eval "(load (expand-file-name \"ar-thingatpt-rest-list-in-region-only.el\"))" \
            --eval "(load (expand-file-name \"ar-sexp.el\"))" \
            --eval "(load (expand-file-name \"ar-comment-lor.el\"))" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thingatpt-setup-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/py-setup-ert-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thingatpt-utils-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-paired-delimit-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-trim-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-bracketlist-atpt-ert-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thingatpt-more-delimited-test.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thingatpt-utils-forward-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-translate-paired-delimiters-test.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-translate-paired-delimiters-test.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thingatpt-utils-delimited-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-list-atpt-brace-ert-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-paired-delimited-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-delimited2delimited-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-separate-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-list-atpt-parens-ert-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thing-atpt-also-delimited-test.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thing-atpt-other-delimited-test.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thing-atpt-other-position-test.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thing-atpt-more-delimited-test.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-thingatpt-utils-comment-or-uncomment-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-forward-sexp-tests.el\")" \
            --eval "(load \"/root/thing-at-point-utils/test/ar-backward-sexp-tests.el\")" \
            --eval "(sit-for 1)" \
            -f ert-run-tests-batch-and-exit


workflows:
  thing-at-point-utils-workflow:
    jobs:
      - thing-at-point-utils  
